### ISSUE TITLE
Add lets encrypt integration using sni challenge.

### ISSUE THREAD

**Issue by creationix** [indutny/bud#102]
It would be really cool if I could configure bud with a list of approved domains, my contact email, and a flag saying I agree to the letsencrypt TOS.  Then when a TLS connection comes in, it will automatically register and cache key/cert pairs using letsencrypt.

**Comment by indutny** [comment]
I believe this is possible with external asynchronous SNI backend, which could be even a node.js server.

**Comment by creationix** [comment]
True.  So you're saying it's out of scope for bud itself then?

**Comment by indutny** [comment]
Yes, the complexity of this feature will be close to the complexity of the project itself.

**Comment by creationix** [comment]
sounds good, thanks anyway!
