### ISSUE TITLE
OpenSSL Engine Support

### ISSUE THREAD

**Issue by swaj** [indutny/bud#70]
It would be awesome if bud supported changing the OpenSSL engine at runtime.  For example, we currently utilize a hardware security module which implements an SSL engine so that keys are stored in hardware, but can be utilized by any program which uses OpenSSL (and allows for the engine to be set).  Would it be possible to add another configuration item for bud?

**Comment by indutny** [comment]
Absolutely! I'll put this in my todo list.

Thanks for asking!

**Comment by indutny** [comment]
@swaj may I ask you to give a try to https://github.com/indutny/bud/pull/71 ? It is pretty hard to test those OpenSSL engines without having `.so` file and actual engine, so I would really appreciate your feedback ;)

**Comment by swaj** [comment]
Sure. I'll test this when I get to work. Thanks!

**Comment by indutny** [comment]
@swaj did you get a chance to try it out?
