### ISSUE TITLE
Too many prepend proxyline calls

### ISSUE THREAD

**Issue by databeille** [indutny/bud#79]
Good day,

I added a new cert to my server today. When testing with ssllabs.com, bud dies returning: 

(dbg) [7222] client 0x2146490 on backend write_cb => 196
(dbg) [7222] client 0x2146490 on frontend SSL_read() => -1
(dbg) [7222] client 0x2146490 on frontend recycle
(dbg) [7222] client 0x2146490 on frontend SSL_read() => -1
(dbg) [7222] client 0x2146490 on frontend after read_cb() => 541
(dbg) [7222] client 0x2146490 on frontend renegotation 0
(dbg) [7222] client 0x2146490 on backend ssl_cert_cb {2}
(dbg) [7222] client 0x2146490 on frontend SSL_read() => -1
Assertion failed ../src/client.c:1052
Too many prepend proxyline calls

Everything used to work fine last time I checked but it was with my old cert, which is not valid anymore.

bud is running on Centos 6.7 x86_64 with <pre> "workers": 0,</pre>

**Comment by databeille** [comment]
It passes with <pre>  "workers": 4,</pre> but I believe it is just a matter of time.

**Comment by indutny** [comment]
Thank you so much for reporting this. I'm working on a fix and should publish it soon!

**Comment by indutny** [comment]
@databeille may I ask you to give a try to the following patch?

```diff
diff --git a/src/client.c b/src/client.c
index 34fe283..9ff92e6 100644
--- a/src/client.c
+++ b/src/client.c
@@ -629,6 +629,10 @@ bud_client_error_t bud_client_backend_out(bud_client_t* client) {
     read = SSL_read(client->ssl, out, avail);
     init_trigger ^= SSL_is_init_finished(client->ssl);
 
+    /* Do not try to prepend proxyline on renegotiation */
+    if (SSL_total_renegotiations(client->ssl) != 0)
+      init_trigger = 0;
+
     DBG(&client->frontend, "SSL_read() => %d", read);
     if (read > 0)
       ringbuffer_write_append(&client->backend.output, read);
```

I'm going to work on test for this, and feedback will be more than welcome!

**Comment by indutny** [comment]
The fix has been landed, but nevertheless I would like to ask you to confirm that it is working for you. Thanks!

**Comment by databeille** [comment]
Fix applied, it works well :)
Thanks.

**Comment by indutny** [comment]
Thank you for using it! ;)
