### ISSUE TITLE
Compatibility with Python3-by-default

### ISSUE THREAD

**Issue by alex-shpilkin** [indutny/bud#81]
Systems with `python` linked to `python3` instead of `python2` (see [PEP 0394](https://www.python.org/dev/peps/pep-0394/)) require the shebang line of `gyp_bud` to be changed from `/usr/bin/env python` to `/usr/bin/env python2`.

<sup>Yes, this is a one-character change, which is why I didn’t create a PR for it.</sup>

**Comment by indutny** [comment]
Thanks for opening this!

Honestly saying, I don't know if I would like to change it at this time. It appears to me that many major projects are using `python` without any problems now. (Including [node][0])

Is it causing problems for you, or is it just a hypothetical case?

[0]: https://github.com/nodejs/node/blob/master/configure#L1

**Comment by alex-shpilkin** [comment]
I’m on Arch Linux, which is a rolling-release distribution and [links `python` to `python3`](https://wiki.archlinux.org/index.php/Python#Dealing_with_version_problem_in_build_scripts). Apparently, even the PEP is motivated by its example. Although, well, node itself using `python` is a valid rebuttal. (See how Arch [handles it for node](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/nodejs#n27).)

**Comment by indutny** [comment]
Alright then! Should be fixed now :) Thank you! :+1:
