### ISSUE TITLE
`bud` is now available on npm

### ISSUE THREAD

**Issue by wltsmrz** [indutny/bud#82]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.915w61wn8

**Comment by indutny** [comment]
Ahaha!

**Comment by tejasmanohar** [comment]
hahaha can't believe this is an issue :P

**Comment by wltsmrz** [comment]
Just thought I'd let you know before someone else snags it, but apparently:

`This package name is not currently in use, but was formerly occupied by a popular package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we\'ll probably give it to you if you want it.`
