### ISSUE TITLE
Getting client cert's distinguished name

### ISSUE THREAD

**Issue by cstrahan** [indutny/bud#85]
Would it be possible to provide access to the distinguished name of the connected client's cert, perhaps via a header and/or the JSON proxyline? (If something like this is already support, it looks like I missed - sorry!)

**Comment by cstrahan** [comment]
I suppose while we're at it, it might make sense to provide access to the other cert details too. Something like this might provide inspiration: https://raymii.org/s/tutorials/haproxy_client_side_ssl_certificates.html

**Comment by indutny** [comment]
Have you seen `proxyline: json` option? I think it should send something like:

```
BUD {"family":"TCP4","bud":{"host":"...","port":...},"peer":{"host":"...","port":"...","cn":"..."}
```

According to readme (and some digging into the source: https://github.com/indutny/bud/blob/1c452759492c52c49eacef4e155a12ebbb1bf37a/src/config.c#L1025-L1034

**Comment by indutny** [comment]
So basically you also want to have `issuer`,`sha`,`dn`,`not-before`,and `not-after`? I don't think that we allow non-verified clients atm, so `verified` does not really make much sense.

**Comment by cstrahan** [comment]
@indutny 

Sorry, lost track of this issue.

> So basically you also want to have `issuer`,`sha`,`dn`,`not-before`,and `not-after`?

Yes -- in my case, particularly the `dn`.

**Comment by indutny** [comment]
Ok, let's start small! 😉 Added `dn`. Thank you for reporting it!

**Comment by cstrahan** [comment]
Awesome - thanks a ton! :smile:
