### ISSUE TITLE
Collecting data about bud usage

### ISSUE THREAD

**Issue by indutny** [indutny/bud#86]
Hello everyone!

Just wanted to let you know that I have created a wiki page, where I am trying to populate some data about companies/projects using bud. This is going to be used for two purposes:
- Informing about security releases
- Possibly convincing other people to use bud, by linking this page on the readme

If any of this sounds interesting - please add some info on [this wiki page](https://github.com/indutny/bud/wiki/Companies-that-use-bud). If you'd like to subscribe to the security releases, but do not want to be listed at any public source (or if you'd like to be listed without contact information) - please do not hesitate to contact me directly ( fedor@indutny.com ).

cc @phillipp @joeybaker @cstrahan @indexzero @swaj ...

**Comment by indutny** [comment]
cc @Acconut

**Comment by joeybaker** [comment]
Sounds great. Added my name. Thanks @indutny!

**Comment by indexzero** [comment]
This is awesome! I'll keep an eye out for it, but we're not using `bud` in production right now. I'd love to change that and these kinds of success stories are a great way to help do that 💯

**Comment by phillipp** [comment]
I have added our company to the list and wrote a paragraph about our use case (and some praise for the project). I think the use case makes the reference more meaningful, but if it's too much I can shorten or remove it.

**Comment by indutny** [comment]
@phillipp thank you, this is indeed very meaningful!
