### ISSUE TITLE
daemon flag causes bud not to run at all

### ISSUE THREAD

**Issue by nkcmr** [indutny/bud#87]
trying to pass the `--daemon` flag to bud does nothing. i was expecting it to run, then detach itself from the current session and run in the background. after running:
```
root@eos:~# ./bud/bin/bud --daemon --config [redacted]/config/bud.production.json 
root@eos:~# 
```
it does not output anything and checking `ps aux | grep bud` doesn't yield any running bud daemon processes. and making requests to buds frontend port (443) fails with connection refused errors (indicating nothing is running)

running bud without the daemon flag and the same configuration starts bud normally and there is a healthy connection made between frontend and backend and requests are working as expected.
```
root@eos:~# ./bud/bin/bud --config [redacted]/config/bud.production.json 
(inf) [2242] spawned bud worker<2243>
(inf) [2242] spawned bud worker<2244>
(inf) [2242] spawned bud worker<2245>
(inf) [2243] Worker updated ticket key for context: 0
(inf) [2242] spawned bud worker<2246>
(inf) [2242] bud listening on [0.0.0.0]:443 and...
(inf) [2242] ...forwarding to: [127.0.0.1]:38872
(inf) [2244] Worker updated ticket key for context: 0
(inf) [2245] Worker updated ticket key for context: 0
(inf) [2246] Worker updated ticket key for context: 0
```

I am running the latest version of bud (v4.0.2) on a DigitalOcean droplet (Ubuntu 14.04.4 x64). I see the same thing happening on my Mac running OS X 10.11.4.

Hopefully, I am not misunderstanding the use of the daemon flag. Thanks for any help whatsoever.

**Comment by indutny** [comment]
Hello!

I have just pushed out bud@4.0.3 that should print configuration error messages when starting it `-d` mode. May I ask you to give it a try and let me know what it will tell you?

Thank you,
Fedor.

**Comment by nkcmr** [comment]
thanks for the quick response @indutny 
i rebuilt bud on my server and tried running with the daemon flag and this was returned:
```
root@eos:~# ./bud/out/Release/bud --daemon --config [redacted]/config/bud.production.json 
root@eos:~# open([redacted]/config/bud.production.json) failed
```
a simple failure to open the config file. interesting. so i ran again, but this time I appended the full path
```
root@eos:~# ./bud/out/Release/bud --daemon --config $HOME/[redacted]/config/bud.production.json 
[normal output for bud indicating successful worker startup]
```
when i appended the full path, it worked as normal, and processes were launched in the background and everything worked as expected.

so, without the `--daemon` flag, relative paths work for `--config`, and with the flag, it has to be absolute. not a big issue, i am already able to get my production app deployed and everything works fine.

thanks for the help and this awesome tool.

**Comment by indutny** [comment]
Thank you for checking it!

Please consider using google form if you'd like to be notified about security releases of bud: https://github.com/indutny/bud#security
