### ISSUE TITLE
Install fails on SmartOS: Ninja prebuild step does not detect platform

### ISSUE THREAD

**Issue by doublerebel** [indutny/bud#91]
Hello,

This latest release using ninja/gyp.js/ninja.js fails to build on SmartOS. none of the solaris-specific flags end up in the `.ninja` files.  I was able to manually change and add the correct cflags, ldflags, and defines, to the `.ninja` files for bud and libuv and build.  I had to add libuv's `unix/sunos.c` to the `.ninja` file for libuv also. (I pulled all the necessary information from the `.gyp` files.)

This is my first time building bud since the build system changed.

I'm not sure exactly where the bug is, but I think this relates to [indutny/gyp.js#1](https://github.com/indutny/gyp.js/issues/1).  I tried several ways to trace it but this is a very new build system for me!  **ninja-build** is available from pkgsrc for SmartOS and seems to have no issues.

**Comment by indutny** [comment]
Should be fixed with gyp.js@1.4.14 . Please give it a try!

Sorry for delay!
